// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeStorage } from '@/lib/safeStorage';

const SUPABASE_URL = "https://jtpiybdcuawhnfibrdho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cGl5YmRjdWF3aG5maWJyZGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Njg1NTksImV4cCI6MjA3MDE0NDU1OX0.wwZA1XoU1No8vqDX-ridfH2PqDrTljWT4--MZdfCI7k";

// Log storage health on initialization
const storageHealth = safeStorage.getStorageHealth();
console.log('[Supabase] Storage health:', storageHealth);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});